### PR TITLE
Implement User Account Page

### PR DESCRIPTION
**Pull request by Jawuah1**
Task #13 Created Account setting page to allow the user to update username and name

### CODE REVIEW

**Review by Jawuah1 — COMMENTED** [review]
Pulled latest changes

**Review by brightodedo — DISMISSED** [review]
Looks Good To Me. I pulled the code and ran it. It is working

**Review by brightodedo — DISMISSED** [review]

**Review by brightodedo — DISMISSED** [review]
I approve

**Review by brightodedo — APPROVED** [review]
Approved

**Pull request merged**
